%YAML 1.2
---
dataset:
    name: "squad"
    n_train: 5000
    n_val: 500

model:
    base_model: "distilbert-base-cased"

freeze:
    strategy: "all_but_last_n"
    args:
        n: 1

train:
    weight_decay: 0.01
    num_train_epochs: 5
    learning_rate: 0.00002
    per_device_train_batch_size: 16
    per_device_eval_batch_size: 16
    output_dir: "results"
    evaluation_strategy: "epoch"
...
