%YAML 1.2
---
dataset:
    name: "sst2"

model:
    base_model: "distilbert-base-cased"

freeze:
    strategy: "none"

train:
    weight_decay: 0.01
    num_train_epochs: 5
    learning_rate: 0.00002
    per_device_train_batch_size: 16
    per_device_eval_batch_size: 16
    output_dir: "results"
    evaluation_strategy: "epoch"

evaluate:
    metric_function: "accuracy"
...
