%YAML 1.2
---
dataset:
    name: "sst2"

model:
    base_model: "distilbert-base-cased"
    model_type: "bert"
    lora:
        scaling_rank: 1
        rank: 0
        init_scale: 0.00
        layers: "lin1|lin2"
        modules: ".*ffn"
        buffer_original: False

freeze:
    strategy: "none"

adapter:
    strategy: "none"

optimizer:
    name: "adafactor"
    lr: 0.003
    weight_decay: 0
    scale_parameter: True
    scheduler: "linear_decay_with_warmup"
    warmup_ratio: 0.06
    trainable_param_names: ".*lora_b.*"

train:
    num_train_epochs: 5
    per_device_train_batch_size: 16
    per_device_eval_batch_size: 16
    output_dir: "results"
    evaluation_strategy: "epoch"

...
