%YAML 1.2
---
dataset:
    name: "sst2"

model:
    base_model: "roberta-large"
    model_type: "bert"

freeze:
    strategy: "none"

adapter:
    strategy: "none"

optimizer:
    name: "adamw"
    lr: 0.00001
    weight_decay: 0.01
    scheduler: "linear_decay_with_warmup"
    warmup_ratio: 0.06

train:
    num_train_epochs: 20
    per_device_train_batch_size: 16
    per_device_eval_batch_size: 16
    output_dir: "results"
    evaluation_strategy: "steps"
    eval_steps: 500
    save_strategy: "epoch"
    save_total_limit: 50

...
