%YAML 1.2
---
dataset:
    name: "sst2"

model:
    base_model: "distilbert-base-cased"
    modifier: "lora"

freeze:
    strategy: "none"

optimizer:
    name: "adafactor"
    lr: 0.003
    weight_decay: 0
    scale_parameter: True
    scheduler: "linear_decay_with_warmup"
    warmup_ratio: 0.06

train:
    num_train_epochs: 5
    per_device_train_batch_size: 16
    per_device_eval_batch_size: 16
    output_dir: "results"
    evaluation_strategy: "epoch"

evaluate:
    metric_function: "accuracy"
...
