%YAML 1.2
---
dataset:
    name: "sst2"

model:
    base_model: "roberta-large"
    model_type: "bert"
    modifier: "mezo"
    modifier_args:
        eps: 0.001
        pos_label: "great"
        neg_label: "terrible"

freeze:
    strategy: "all_but_last_n"
    args:
        n: 0

adapter:
    strategy: "none"

optimizer:
    name: "sgd"
    lr: 0.000001
    weight_decay: 0.01
    scale_parameter: True
    scheduler: "constant"
    warmup_ratio: 0

train:
    num_train_epochs: 5
    per_device_train_batch_size: 16
    per_device_eval_batch_size: 16
    output_dir: "results"
    evaluation_strategy: "steps"
    eval_steps: 500
    logging_steps: 100
    save_total_limit: 5
    save_strategy: "steps"
    save_steps: 1000
    max_steps: 100000

...
