%YAML 1.2
---
dataset:
    name: "sst2"

model:
    base_model: "roberta-large"
    model_type: "bert prompt"
    modifier: "prompt"
    modifier_args:
        pos_label: "great"
        neg_label: "terrible"

freeze:
    strategy: "all_but_last_n"
    args:
        n: 0

adapter:
    strategy: "lst"
    args:
        reduction_factor: 8
        fusion: "attention" # "additive", "dynamic", "gated" or "attention"

optimizer:
    name: "adamw"
    lr: 0.00002
    weight_decay: 0.01
    scale_parameter: True
    scheduler: "linear_decay_with_warmup"
    warmup_ratio: 0.06

train:
    num_train_epochs: 5
    per_device_train_batch_size: 16
    per_device_eval_batch_size: 16
    output_dir: "results"
    evaluation_strategy: "steps"
    eval_steps: 500
    logging_steps: 10
    save_strategy: "no"
...
