%YAML 1.2
---
dataset:
    name: "sst2"

model:
    base_model: "roberta-large"
    model_type: "bert"
    lora:
        scaling_rank: 0
        rank: 4
        init_scale: 0.01
        layers: "query|key|value|dense"
        modules: ".*self|.*output|.*intermediate"
        buffer_original: True

freeze:
    strategy: "none"

optimizer:
    name: "adamw"
    lr: 0.00006
    weight_decay: 0.01
    scheduler: "linear_decay_with_warmup"
    warmup_ratio: 0.06
    trainable_param_names: "classifier.dense.*|.*out_proj.*|.*LayerNorm.*|.*lora_[ab].*"

train:
    num_train_epochs: 5
    per_device_train_batch_size: 16
    per_device_eval_batch_size: 16
    output_dir: "results"
    evaluation_strategy: "epoch"

...
