%YAML 1.2
---
dataset:
    name: "sst2"

model:
    base_model: "distilbert-base-cased"
    model_type: "bert"

freeze:
    strategy: "none"

optimizer:
    name: "sgd"
    lr: 0.00001
    weight_decay: 0.01
    scale_parameter: True
    scheduler: "constant"
    warmup_ratio: 0

train:
    num_train_epochs: 5
    per_device_train_batch_size: 16
    per_device_eval_batch_size: 16
    output_dir: "results"
    evaluation_strategy: "epoch"
    save_strategy: "no"

...
